_name_: the_pile
dataset_name: '/home/avi_keinan_a_k/data/code/python/final/jsonl/test/new_python_test_0_text.jsonl' #'/home/avi_keinan_a_k/git_repos/safari_local/data/pile/00.jsonl'
dataset_config_name: null
tokenizer_name: gpt2
cache_dir: ${oc.env:DATA_PATH}/the_pile/cache
max_length: 2048
add_eos: True
batch_size: 4  # per GPU
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 18  # For preprocessing only
use_shmem: False
shuffle: True
pin_memory: True
__train_len: ${div_up:374337375694, ${.max_length}}
__l_max: ${.max_length}